typography_spectrum: 0.18479642691090703
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.8911944841966033
  lightness: 0.19888293463736773
  saturation: 0.8315825185272843
  rhythmicContrast: 0.3246730831451714
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8608463397249579
analytics:
  google: null
  facebook: null
  twitter: null
name: Personal coaching
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Sports Performance &                     Personal Coaching
purpose: []
