typography_spectrum: 0.20799
color:
  brandColors:
    - '#FFFFFF'
    - '#D11900'
    - '#000000'
    - '#C4C4C4'
    - '#D35B2F'
  brandStrength: 0.8911944841966033
  lightness: 0.4964158
  saturation: 0.8315825
  rhythmicContrast: 0.297491
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21797
analytics:
  google: null
  facebook: null
  twitter: null
name: "BodyProject\_"
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact us
    id: 67926e8f-57e4-4395-afa5-dab188e67ece
    type: content
  - name: About us
    id: 9b66640a-c990-4205-a508-12c1acce9b7a
    type: content
  - name: Services
    id: 2e71b63b-370e-4144-9aea-80cf44575f42
    type: content
  - name: 'Training systems '
    id: 8141d20a-5018-4e1f-a3d1-db901ead8d75
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
purpose: []
