typography_spectrum: 0.3584229
color:
  brandColors:
    - '#FFFFFF'
    - '#D11900'
    - '#000000'
    - '#C4C4C4'
    - '#D35B2F'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13568
analytics:
  google: null
  facebook: null
  twitter: null
name: BodyProject PC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Services
    id: 2e71b63b-370e-4144-9aea-80cf44575f42
    type: content
  - name: About us
    id: 9b66640a-c990-4205-a508-12c1acce9b7a
    type: content
  - name: Contact us
    id: 67926e8f-57e4-4395-afa5-dab188e67ece
    type: content
  - name: 'Training systems '
    id: 8141d20a-5018-4e1f-a3d1-db901ead8d75
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: BodyProjectPC
description: "Personal Coaching & Sports Performance\_"
purpose: []
